version: '3.8'

services:
  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php_app_image
    ports:
      - "8080:80"  # Map port 80 in the container to port 8080 on your host

